// Code generated by "stringer -type=LogCategory"; DO NOT EDIT.

package enums

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[Info-0]
	_ = x[Debug-1]
	_ = x[Warn-2]
	_ = x[Error-3]
	_ = x[Fatal-4]
}

const _LogCategory_name = "InfoDebugWarnErrorFatal"

var _LogCategory_index = [...]uint8{0, 4, 9, 13, 18, 23}

func (i LogCategory) String() string {
	if i < 0 || i >= LogCategory(len(_LogCategory_index)-1) {
		return "LogCategory(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _LogCategory_name[_LogCategory_index[i]:_LogCategory_index[i+1]]
}
