---
name: Test & Validate Migrations

on:
  pull_request:
    branches: [master, dev]

  push:
    branches: [master, dev]

jobs:
  test:
    if: github.actor != 'release-please[bot]'
    runs-on: ubuntu-latest
    strategy:
      matrix:
        pkg: [./cmd/apply, ./cmd/create, ./cmd/init]
    services:
      postgres:
        image: postgres:15
        env:
          POSTGRES_USER: testuser
          POSTGRES_PASSWORD: testpass
          POSTGRES_DB: testdb
        ports: [5432:5432]
        options: >-
          --health-cmd="pg_isready"
          --health-interval=10s
          --health-timeout=5s
          --health-retries=5
    env:
      DATABASE_URL: postgres://testuser:testpass@localhost:5432/testdb?sslmode=disable

    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v5
        with:
          go-version: '1.22'
          cache: false

      - name: Wait for DB to be ready
        run: |
          until pg_isready -h localhost -p 5432; do sleep 1; done

      - name: Run Tests for ${{matrix.pkg}}
        run: go test ${{matrix.pkg}}/... -v
