// Code generated by "stringer -type=postStatusEnum"; DO NOT EDIT.

package apply

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[NoExist-0]
	_ = x[Pending-1]
	_ = x[Applied-2]
}

const _postStatusEnum_name = "NoExistPendingApplied"

var _postStatusEnum_index = [...]uint8{0, 7, 14, 21}

func (i postStatusEnum) String() string {
	if i < 0 || i >= postStatusEnum(len(_postStatusEnum_index)-1) {
		return "postStatusEnum(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _postStatusEnum_name[_postStatusEnum_index[i]:_postStatusEnum_index[i+1]]
}
